[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev"

[functions]
  included_files = ["**/*.ts", "**/*.json"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
